// Subscription state mirrored from RevenueCat into users/{uid}.subscription.
//
// Source of truth: RevenueCat (App Store / Google Play / Stripe). This
// struct is written by the `revenueCatWebhook` Cloud Function and read
// by the client for gating and UI display. Do NOT mutate it from the
// client — the only authoritative path is RevenueCat → webhook → Firestore.
//
// Hand-maintained: if this file is regenerated by FlutterFlow, restore
// the subscription-related fields. The companion users_record.dart entry
// and TypeTransactions enum extension must also be preserved together.

// ignore_for_file: unnecessary_getters_setters

import 'package:cloud_firestore/cloud_firestore.dart';

import '/backend/schema/util/firestore_util.dart';

import '/flutter_flow/flutter_flow_util.dart';

class SubscriptionStruct extends FFFirebaseStruct {
  SubscriptionStruct({
    String? entitlementId,
    String? productId,
    String? pendingProductId,
    int? periodMonths,
    DateTime? startedAt,
    DateTime? expiresAt,
    bool? willRenew,
    String? store,
    String? revenueCatUserId,
    String? originalTransactionId,
    String? environment,
    String? periodType,
    String? lastEventType,
    DateTime? lastEventAt,
    FirestoreUtilData firestoreUtilData = const FirestoreUtilData(),
  })  : _entitlementId = entitlementId,
        _productId = productId,
        _pendingProductId = pendingProductId,
        _periodMonths = periodMonths,
        _startedAt = startedAt,
        _expiresAt = expiresAt,
        _willRenew = willRenew,
        _store = store,
        _revenueCatUserId = revenueCatUserId,
        _originalTransactionId = originalTransactionId,
        _environment = environment,
        _periodType = periodType,
        _lastEventType = lastEventType,
        _lastEventAt = lastEventAt,
        super(firestoreUtilData);

  // "entitlementId" field.
  String? _entitlementId;
  String get entitlementId => _entitlementId ?? '';
  set entitlementId(String? val) => _entitlementId = val;

  bool hasEntitlementId() => _entitlementId != null;

  // "productId" field.
  String? _productId;
  String get productId => _productId ?? '';
  set productId(String? val) => _productId = val;

  bool hasProductId() => _productId != null;

  // "pendingProductId" field — deferred upgrade/downgrade target.
  String? _pendingProductId;
  String get pendingProductId => _pendingProductId ?? '';
  set pendingProductId(String? val) => _pendingProductId = val;

  bool hasPendingProductId() => _pendingProductId != null;

  // "periodMonths" field.
  int? _periodMonths;
  int get periodMonths => _periodMonths ?? 0;
  set periodMonths(int? val) => _periodMonths = val;

  bool hasPeriodMonths() => _periodMonths != null;

  // "startedAt" field.
  DateTime? _startedAt;
  DateTime? get startedAt => _startedAt;
  set startedAt(DateTime? val) => _startedAt = val;

  bool hasStartedAt() => _startedAt != null;

  // "expiresAt" field — the gating signal. If null or in the past, the
  // user has no active subscription.
  DateTime? _expiresAt;
  DateTime? get expiresAt => _expiresAt;
  set expiresAt(DateTime? val) => _expiresAt = val;

  bool hasExpiresAt() => _expiresAt != null;

  // "willRenew" field.
  bool? _willRenew;
  bool get willRenew => _willRenew ?? false;
  set willRenew(bool? val) => _willRenew = val;

  bool hasWillRenew() => _willRenew != null;

  // "store" field — "app_store", "play_store", "stripe", "promotional",
  // "trial", or "unknown".
  String? _store;
  String get store => _store ?? '';
  set store(String? val) => _store = val;

  bool hasStore() => _store != null;

  // "revenueCatUserId" field.
  String? _revenueCatUserId;
  String get revenueCatUserId => _revenueCatUserId ?? '';
  set revenueCatUserId(String? val) => _revenueCatUserId = val;

  bool hasRevenueCatUserId() => _revenueCatUserId != null;

  // "originalTransactionId" field.
  String? _originalTransactionId;
  String get originalTransactionId => _originalTransactionId ?? '';
  set originalTransactionId(String? val) => _originalTransactionId = val;

  bool hasOriginalTransactionId() => _originalTransactionId != null;

  // "environment" field — "PRODUCTION" or "SANDBOX".
  String? _environment;
  String get environment => _environment ?? '';
  set environment(String? val) => _environment = val;

  bool hasEnvironment() => _environment != null;

  // "periodType" field — "TRIAL", "NORMAL", "INTRO", "PROMOTIONAL".
  String? _periodType;
  String get periodType => _periodType ?? '';
  set periodType(String? val) => _periodType = val;

  bool hasPeriodType() => _periodType != null;

  // "lastEventType" field — last RevenueCat event we processed for this
  // subscription (INITIAL_PURCHASE, RENEWAL, CANCELLATION, …).
  String? _lastEventType;
  String get lastEventType => _lastEventType ?? '';
  set lastEventType(String? val) => _lastEventType = val;

  bool hasLastEventType() => _lastEventType != null;

  // "lastEventAt" field.
  DateTime? _lastEventAt;
  DateTime? get lastEventAt => _lastEventAt;
  set lastEventAt(DateTime? val) => _lastEventAt = val;

  bool hasLastEventAt() => _lastEventAt != null;

  static SubscriptionStruct fromMap(Map<String, dynamic> data) =>
      SubscriptionStruct(
        entitlementId: data['entitlementId'] as String?,
        productId: data['productId'] as String?,
        pendingProductId: data['pendingProductId'] as String?,
        periodMonths: castToType<int>(data['periodMonths']),
        startedAt: data['startedAt'] as DateTime?,
        expiresAt: data['expiresAt'] as DateTime?,
        willRenew: data['willRenew'] as bool?,
        store: data['store'] as String?,
        revenueCatUserId: data['revenueCatUserId'] as String?,
        originalTransactionId: data['originalTransactionId'] as String?,
        environment: data['environment'] as String?,
        periodType: data['periodType'] as String?,
        lastEventType: data['lastEventType'] as String?,
        lastEventAt: data['lastEventAt'] as DateTime?,
      );

  static SubscriptionStruct? maybeFromMap(dynamic data) => data is Map
      ? SubscriptionStruct.fromMap(data.cast<String, dynamic>())
      : null;

  Map<String, dynamic> toMap() => {
        'entitlementId': _entitlementId,
        'productId': _productId,
        'pendingProductId': _pendingProductId,
        'periodMonths': _periodMonths,
        'startedAt': _startedAt,
        'expiresAt': _expiresAt,
        'willRenew': _willRenew,
        'store': _store,
        'revenueCatUserId': _revenueCatUserId,
        'originalTransactionId': _originalTransactionId,
        'environment': _environment,
        'periodType': _periodType,
        'lastEventType': _lastEventType,
        'lastEventAt': _lastEventAt,
      }.withoutNulls;

  @override
  Map<String, dynamic> toSerializableMap() => {
        'entitlementId': serializeParam(_entitlementId, ParamType.String),
        'productId': serializeParam(_productId, ParamType.String),
        'pendingProductId': serializeParam(_pendingProductId, ParamType.String),
        'periodMonths': serializeParam(_periodMonths, ParamType.int),
        'startedAt': serializeParam(_startedAt, ParamType.DateTime),
        'expiresAt': serializeParam(_expiresAt, ParamType.DateTime),
        'willRenew': serializeParam(_willRenew, ParamType.bool),
        'store': serializeParam(_store, ParamType.String),
        'revenueCatUserId': serializeParam(_revenueCatUserId, ParamType.String),
        'originalTransactionId':
            serializeParam(_originalTransactionId, ParamType.String),
        'environment': serializeParam(_environment, ParamType.String),
        'periodType': serializeParam(_periodType, ParamType.String),
        'lastEventType': serializeParam(_lastEventType, ParamType.String),
        'lastEventAt': serializeParam(_lastEventAt, ParamType.DateTime),
      }.withoutNulls;

  static SubscriptionStruct fromSerializableMap(Map<String, dynamic> data) =>
      SubscriptionStruct(
        entitlementId:
            deserializeParam(data['entitlementId'], ParamType.String, false),
        productId: deserializeParam(data['productId'], ParamType.String, false),
        pendingProductId:
            deserializeParam(data['pendingProductId'], ParamType.String, false),
        periodMonths:
            deserializeParam(data['periodMonths'], ParamType.int, false),
        startedAt:
            deserializeParam(data['startedAt'], ParamType.DateTime, false),
        expiresAt:
            deserializeParam(data['expiresAt'], ParamType.DateTime, false),
        willRenew: deserializeParam(data['willRenew'], ParamType.bool, false),
        store: deserializeParam(data['store'], ParamType.String, false),
        revenueCatUserId:
            deserializeParam(data['revenueCatUserId'], ParamType.String, false),
        originalTransactionId: deserializeParam(
            data['originalTransactionId'], ParamType.String, false),
        environment:
            deserializeParam(data['environment'], ParamType.String, false),
        periodType:
            deserializeParam(data['periodType'], ParamType.String, false),
        lastEventType:
            deserializeParam(data['lastEventType'], ParamType.String, false),
        lastEventAt:
            deserializeParam(data['lastEventAt'], ParamType.DateTime, false),
      );

  @override
  String toString() => 'SubscriptionStruct(${toMap()})';

  @override
  bool operator ==(Object other) {
    return other is SubscriptionStruct &&
        entitlementId == other.entitlementId &&
        productId == other.productId &&
        pendingProductId == other.pendingProductId &&
        periodMonths == other.periodMonths &&
        startedAt == other.startedAt &&
        expiresAt == other.expiresAt &&
        willRenew == other.willRenew &&
        store == other.store &&
        revenueCatUserId == other.revenueCatUserId &&
        originalTransactionId == other.originalTransactionId &&
        environment == other.environment &&
        periodType == other.periodType &&
        lastEventType == other.lastEventType &&
        lastEventAt == other.lastEventAt;
  }

  @override
  int get hashCode => const ListEquality().hash([
        entitlementId,
        productId,
        pendingProductId,
        periodMonths,
        startedAt,
        expiresAt,
        willRenew,
        store,
        revenueCatUserId,
        originalTransactionId,
        environment,
        periodType,
        lastEventType,
        lastEventAt,
      ]);
}

SubscriptionStruct createSubscriptionStruct({
  String? entitlementId,
  String? productId,
  String? pendingProductId,
  int? periodMonths,
  DateTime? startedAt,
  DateTime? expiresAt,
  bool? willRenew,
  String? store,
  String? revenueCatUserId,
  String? originalTransactionId,
  String? environment,
  String? periodType,
  String? lastEventType,
  DateTime? lastEventAt,
  Map<String, dynamic> fieldValues = const {},
  bool clearUnsetFields = true,
  bool create = false,
  bool delete = false,
}) =>
    SubscriptionStruct(
      entitlementId: entitlementId,
      productId: productId,
      pendingProductId: pendingProductId,
      periodMonths: periodMonths,
      startedAt: startedAt,
      expiresAt: expiresAt,
      willRenew: willRenew,
      store: store,
      revenueCatUserId: revenueCatUserId,
      originalTransactionId: originalTransactionId,
      environment: environment,
      periodType: periodType,
      lastEventType: lastEventType,
      lastEventAt: lastEventAt,
      firestoreUtilData: FirestoreUtilData(
        clearUnsetFields: clearUnsetFields,
        create: create,
        delete: delete,
        fieldValues: fieldValues,
      ),
    );

SubscriptionStruct? updateSubscriptionStruct(
  SubscriptionStruct? subscription, {
  bool clearUnsetFields = true,
  bool create = false,
}) =>
    subscription
      ?..firestoreUtilData = FirestoreUtilData(
        clearUnsetFields: clearUnsetFields,
        create: create,
      );

void addSubscriptionStructData(
  Map<String, dynamic> firestoreData,
  SubscriptionStruct? subscription,
  String fieldName, [
  bool forFieldValue = false,
]) {
  firestoreData.remove(fieldName);
  if (subscription == null) {
    return;
  }
  if (subscription.firestoreUtilData.delete) {
    firestoreData[fieldName] = FieldValue.delete();
    return;
  }
  final clearFields =
      !forFieldValue && subscription.firestoreUtilData.clearUnsetFields;
  if (clearFields) {
    firestoreData[fieldName] = <String, dynamic>{};
  }
  final subscriptionData =
      getSubscriptionFirestoreData(subscription, forFieldValue);
  final nestedData =
      subscriptionData.map((k, v) => MapEntry('$fieldName.$k', v));

  final mergeFields = subscription.firestoreUtilData.create || clearFields;
  firestoreData
      .addAll(mergeFields ? mergeNestedFields(nestedData) : nestedData);
}

Map<String, dynamic> getSubscriptionFirestoreData(
  SubscriptionStruct? subscription, [
  bool forFieldValue = false,
]) {
  if (subscription == null) {
    return {};
  }
  final firestoreData = mapToFirestore(subscription.toMap());

  // Add any Firestore field values
  subscription.firestoreUtilData.fieldValues
      .forEach((k, v) => firestoreData[k] = v);

  return forFieldValue ? mergeNestedFields(firestoreData) : firestoreData;
}

List<Map<String, dynamic>> getSubscriptionListFirestoreData(
  List<SubscriptionStruct>? subscriptions,
) =>
    subscriptions?.map((e) => getSubscriptionFirestoreData(e, true)).toList() ??
    [];
